
# 1. Coordinate del database (Nota che c'è scritto /gestione_aule alla fine)
spring.datasource.url=jdbc:mysql://localhost:3306/gestione_aule?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

# 2. Mostra le query SQL nella console (utile per capire cosa fa)
spring.jpa.show-sql=true

# 3. IL COMANDO MAGICO: Crea e aggiorna le tabelle automaticamente
spring.jpa.hibernate.ddl-auto=update

server.port=8081